# Generated by Django 2.0.4 on 2018-05-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_auto_20180427_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=50)),
                ('juzgado', models.CharField(max_length=50)),
                ('n_cuenta_1', models.CharField(max_length=50)),
                ('n_cuenta_2', models.CharField(max_length=50)),
                ('endoso', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, max_length=15, null=True)),
                ('idlistado', models.IntegerField()),
                ('idorden', models.IntegerField()),
                ('empresa', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('idcliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Juicio_Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=50)),
                ('juzgado', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('idjuicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juicios.Juicio')),
            ],
        ),
        migrations.CreateModel(
            name='Juicio_Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=50)),
                ('juzgado', models.CharField(max_length=50)),
                ('estado', models.CharField(default='SIN VISAR', max_length=50)),
                ('visado', models.DateTimeField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('idjuicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juicios.Juicio')),
            ],
        ),
    ]
