# Generated by Django 2.0.4 on 2018-05-02 14:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juicio',
            name='estado',
            field=models.CharField(default='NORMAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='n_cuenta_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='n_cuenta_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='observacion',
            field=models.CharField(default='SIN OBSERVACION', max_length=500),
        ),
        migrations.AlterField(
            model_name='juicio',
            name='usuario',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
