# Generated by Django 2.0.4 on 2018-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180427_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_corriente',
            name='cuotas_atrasadas',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cuenta_corriente',
            name='tipo_atraso',
            field=models.CharField(default='SIN ATRASO', max_length=50),
        ),
    ]
