# Generated by Django 2.0.4 on 2018-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_imagen',
            name='imagen',
            field=models.ImageField(upload_to='uploads/images/%Y/%m/%d/'),
        ),
    ]
