# Generated by Django 2.0.4 on 2018-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20180509_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_imagen',
            name='imagen',
            field=models.ImageField(upload_to='Project/static/uploads/images/%Y/%m/%d/'),
        ),
    ]
