# Generated by Django 2.0.4 on 2018-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180509_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_imagen',
            name='imagen',
            field=models.ImageField(upload_to='static/uploads/images/%Y/%m/%d/'),
        ),
    ]
