# Generated by Django 2.0.4 on 2018-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20180509_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_imagen',
            name='imagen',
            field=models.ImageField(upload_to='static/uploads/images/'),
        ),
    ]
