# Generated by Django 2.0.4 on 2018-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20180509_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_imagen',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
