# Generated by Django 2.0.4 on 2018-05-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_auto_20180427_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cuota', models.DateTimeField(auto_now_add=True)),
                ('mes_cuota', models.CharField(max_length=50)),
                ('anio_cuota', models.CharField(max_length=50)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idorden', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('cantidad_cuotas', models.IntegerField()),
                ('capital', models.IntegerField()),
                ('producido', models.IntegerField()),
                ('empresa', models.CharField(max_length=50)),
                ('idgarante', models.IntegerField()),
                ('idvendedor', models.CharField(max_length=50)),
                ('forma_de_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200)),
                ('monto_facturacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_facturacion', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.IntegerField()),
                ('cft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cft2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tea2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('idcliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cuota',
            name='idorden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Orden'),
        ),
    ]
